In [1]:
import numpy as np

In [2]:
X = np.random.normal(loc=10, scale=10, size=(100, 10))
print("Матрица X:\n", X)

Матрица X:
 [[ 2.89027285e+00  1.87760963e+01  2.32138383e+01  3.05159477e+00
   1.79211929e+01  1.60625040e+01  2.08182498e+01 -1.31470008e+00
   2.23941973e+01  1.69887570e+01]
 [ 9.19559388e+00  1.08249895e+01  2.61384977e+01  1.01357999e+01
   4.29519486e+00  1.86524058e+01  4.09509410e+00  3.27310844e+00
   1.27476589e+01  1.93996497e+01]
 [ 1.28873341e+01  1.06685765e+01  2.12848745e+01 -8.40160374e+00
   2.20508096e+01  1.82443260e+00  4.66112558e+00  2.02722709e+01
   1.35741702e+01  6.38944857e+00]
 [ 1.18347589e+01  1.67036409e+01  2.78140924e+01  1.41607766e+01
   9.00324741e+00 -1.38084891e+01  2.56834607e+01  1.72197618e+00
   1.47775124e+01  2.16156667e+01]
 [ 1.49335725e+01 -5.85741067e+00  2.62898777e+01 -2.49893729e+00
   8.50067097e+00  2.91752732e+00  1.49661089e+01  1.35249952e-02
   2.07167080e+01  7.61626785e+00]
 [-9.25665660e+00  1.04314395e+01  1.39540019e+01  1.48604694e+01
   1.34411951e+01  1.93655745e+01  1.19384217e+01  7.11277327e+00
   9.33949942e+00 -1.

In [3]:
mean = np.mean(X, axis=0)
std_dev = np.std(X, axis=0)
normX = (X - mean) / std_dev

print("\nНормированная матрица:\n", normX)


Нормированная матрица:
 [[-6.56797686e-01  9.98253128e-01  1.25924455e+00 -6.64147923e-01
   7.54796874e-01  5.31554258e-01  1.11897178e+00 -1.13285765e+00
   9.86058042e-01  7.69964131e-01]
 [-6.35378476e-02  1.59076045e-01  1.56571190e+00  6.65102213e-02
  -6.87546550e-01  7.91795932e-01 -6.51820042e-01 -6.66183078e-01
   4.67496429e-02  9.91365537e-01]
 [ 2.83813413e-01  1.42567883e-01  1.05711352e+00 -1.84541987e+00
   1.19192635e+00 -8.99133034e-01 -5.91883751e-01  1.06298168e+00
   1.27229183e-01 -2.03410499e-01]
 [ 1.84777920e-01  7.79521688e-01  1.74129306e+00  4.81642470e-01
  -1.89188293e-01 -2.46997938e+00  1.63414223e+00 -8.23965160e-01
   2.44401729e-01  1.19487077e+00]
 [ 4.76341443e-01 -1.60162070e+00  1.58157461e+00 -1.23662449e+00
  -2.42387172e-01 -7.89295355e-01  4.99296673e-01 -9.97749815e-01
   8.22716571e-01 -9.07470390e-02]
 [-1.79968722e+00  1.17539924e-01  2.88930697e-01  5.53808123e-01
   2.80578740e-01  8.63457425e-01  1.78699071e-01 -2.75610123e-01
  -2.851

In [4]:
Z = np.array([[4, 5, 0],
              [1, 9, 3],
              [5, 1, 1],
              [3, 3, 3],
              [9, 9, 9],
              [4, 7, 1]])

row_sums = np.sum(Z, axis=1)
rows_gt_10 = np.nonzero(row_sums > 10)

print("\nИндексы строк, где сумма > 10:\n", rows_gt_10)


Индексы строк, где сумма > 10:
 (array([1, 4, 5]),)


In [5]:
A = np.eye(3)
B = np.eye(3)
AB = np.vstack((A, B))

print("\nМатрица A:\n", A)
print("\nМатрица B:\n", B)
print("\nОбъединённая матрица AB:\n", AB)


Матрица A:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Матрица B:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Объединённая матрица AB:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
